stages:
  - deploy
  
deploy:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker compose -f docker-compose.yml build
    - docker compose -f docker-compose.yml up -d
    - docker ps
  only:
    - main
