image: docker:24
services:
  - docker:24-dind


variables:
  DOCKER_DRIVER: overlay2
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_TLS_CERTDIR: ""


stages:
  - build
  - test
  - deploy


before_script:
  - docker info


build_images:
  stage: build
  script:
  - docker build -t intrack-backend:latest ./backend
  - docker build -t intrack-frontend:latest ./frontend
  artifacts:
    expire_in: 1h
    paths:
    - backend/
    - frontend/


test:
  stage: test
  script:
  - echo "No unit tests configured. Add tests to backend and frontend to run here."


deploy_local:
  stage: deploy
  script:
  - apk add --no-cache py3-pip curl
  - pip3 install docker-compose
  - docker-compose -f docker-compose.yml up -d --build
  only:
  - main